import Navbar from "@/components/page"
import "./globals.css"
import { Inter } from "next/font/google"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        {" "}
        <Navbar /> {children}
      </body>
    </html>
  )
}
